### ISSUE TITLE
Doesn't escape "$"

### ISSUE THREAD

**Issue by CubeRanch** [claudineyqr/vscode-snippets-creator#3]
Works well, but not very useful for PHP. Any variable in selected code doesn't get the dollar sign escaped in the snippet body, so gets stripped out when inserting the snippet.

**Comment by claudineyqr** [comment]
I will carry out the improvement for PHP

**Comment by claudineyqr** [comment]
Improvements made. thanks for the contribution

Release 1.0.2
- Improvements to PHP Language
- Optional Name Snippet
